# Site settings
title: Dino Occhialini
email: dino@occhialini.net
description: > # this means to ignore newlines until "baseurl:"
  I am a network adminstrator and student researcher pursuing a computer science degree at the University of Texas at Dallas.  My interest focus primarily around Linux and Machine Learning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dinoocch.github.io" # the base hostname & protocol for your site
github_username:  dinoocch

# Build settings
markdown: kramdown
